language: java
jdk:
  - openjdk11
script:
  - mvn -Dintegration clean test jacoco:report coveralls:report
after_success:
  - mvn test jacoco:report coveralls:report
cache:
  directories:
    - $HOME/.m2